"use strict";
exports.HEROES = [
    { id: 11, name: 'Mr. Nice',
        description: 'The Tour of Heroes has become more reusable using shared components and services. The next goal is to create a dashboard, add menu links that route between the views, and format data in a template. As the app evolves, you\'ll discover how to design it to make it easier to grow and maintain.' },
    { id: 12, name: 'Narco',
        description: 'The Tour of Heroes has become more reusable using shared components and services. The next goal is to create a dashboard, add menu links that route between the views, and format data in a template. As the app evolves, you\'ll discover how to design it to make it easier to grow and maintain.' },
    { id: 13, name: 'Bombasto',
        description: 'The Tour of Heroes has become more reusable using shared components and services. The next goal is to create a dashboard, add menu links that route between the views, and format data in a template. As the app evolves, you\'ll discover how to design it to make it easier to grow and maintain.' },
    { id: 14, name: 'Celeritas',
        description: 'The Tour of Heroes has become more reusable using shared components and services. The next goal is to create a dashboard, add menu links that route between the views, and format data in a template. As the app evolves, you\'ll discover how to design it to make it easier to grow and maintain. The Tour of Heroes has become more reusable using shared components and services. The next goal is to create a dashboard, add menu links that route between the views, and format data in a template. As the app evolves, you\'ll discover how to design it to make it easier to grow and maintain.' },
    { id: 15, name: 'Magneta Man',
        description: 'The Tour of Heroes has become more reusable using shared components and services. The next goal is to create a dashboard, add menu links that route between the views, and format data in a template. As the app evolves, you\'ll discover how to design it to make it easier to grow and maintain. The Tour of Heroes has become more reusable using shared components and services. The next goal is to create a dashboard, add menu links that route between the views, and format data in a template. As the app evolves, you\'ll discover how to design it to make it easier to grow and maintain.The Tour of Heroes has become more reusable using shared components and services. The next goal is to create a dashboard, add menu links that route between the views, and format data in a template. As the app evolves, you\'ll discover how to design it to make it easier to grow and maintain.' },
    { id: 16, name: 'Rubber Man',
        description: 'The Tour of Heroes has become more reusable using shared components and services. The next goal is to create a dashboard, add menu links that route between the views, and format data in a template. As the app evolves, you\'ll discover how to design it to make it easier to grow and maintain. The Tour of Heroes has become more reusable using shared components and services. The next goal is to create a dashboard, add menu links that route between the views, and format data in a template. As the app evolves, you\'ll discover how to design it to make it easier to grow and maintain. The Tour of Heroes has become more reusable using shared components and services. The next goal is to create a dashboard, add menu links that route between the views, and format data in a template. As the app evolves, you\'ll discover how to design it to make it easier to grow and maintain. The Tour of Heroes has become more reusable using shared components and services. The next goal is to create a dashboard, add menu links that route between the views, and format data in a template. As the app evolves, you\'ll discover how to design it to make it easier to grow and maintain.' },
    { id: 17, name: 'Dynama Kiev',
        description: 'The Tour of Heroes has become more reusable using shared components and services. The next goal is to create a dashboard, add menu links that route between the views, and format data in a template. As the app evolves, you\'ll discover how to design it to make it easier to grow and maintain.' },
    { id: 18, name: 'Dr IQ',
        description: 'The Tour of Heroes has become more reusable using shared components and services. The next goal is to create a dashboard, add menu links that route between the views, and format data in a template. As the app evolves, you\'ll discover how to design it to make it easier to grow and maintain.' },
    { id: 19, name: 'Magma Lava',
        description: 'The Tour of Heroes has become more reusable using shared components and services. The next goal is to create a dashboard, add menu links that route between the views, and format data in a template. As the app evolves, \'ll discover how to design it to make it easier to grow and maintain. The Tour of Heroes has become more reusable using shared components and services. The next goal is to create a dashboard, add menu links that route between the views, and format data in a template. As the app evolves, you\'ll discover how to design it to make it easier to grow and maintain. The Tour of Heroes has become more reusable using shared components and services. The next goal is to create a dashboard, add menu links that route between the views, and format data in a template. As the app evolves, you\'ll discover how to design it to make it easier to grow and maintain. The Tour of Heroes has become more reusable using shared components and services. The next goal is to create a dashboard, add menu links that route between the views, and format data in a template. As the app evolves, you\'ll discover how to design it to make it easier to grow and maintain.' },
    { id: 20, name: 'Tornado Fish',
        description: 'The Tour of Heroes has become more reusable using shared components and services. The next goal is to create a dashboard, add menu links that route between the views, and format data in a template. As the app evolves, you\'ll discover how to design it to make it easier to grow and maintain. The Tour of Heroes has become more reusable using shared components and services. The next goal is to create a dashboard, add menu links that route between the views, and format data in a template. As the app evolves, you\'ll discover how to design it to make it easier to grow and maintain. The Tour of Heroes has become more reusable using shared components and services. The next goal is to create a dashboard, add menu links that route between the views, and format data in a template. As the app evolves, you\'ll discover how to design it to make it easier to grow and maintain. The Tour of Heroes has become more reusable using shared components and services. The next goal is to create a dashboard, add menu links that route between the views, and format data in a template. As the app evolves, you\'ll discover how to design it to make it easier to grow and maintain. The Tour of Heroes has become more reusable using shared components and services. The next goal is to create a dashboard, add menu links that route between the views, and format data in a template. As the app evolves, you\'ll discover how to design it to make it easier to grow and maintain. The Tour of Heroes has become more reusable using shared components and services. ' }
];
//# sourceMappingURL=mock-heroes.js.map